{"name": "Проверка , если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "description": "Проверяем ,что при отсутствии логина,возвращается ошибка и сообщение об ошибке 'Учетная запись не найдена'", "steps": [{"name": "Авторизация курьера с неправильными данными", "status": "passed", "start": 1715428100238, "stop": 1715428100774}], "start": 1715428100237, "stop": 1715428100776, "uuid": "a64b6ed6-cbaa-498f-b018-8bad85df5d94", "historyId": "19cd49565c5ca54056381484040483f5", "testCaseId": "19cd49565c5ca54056381484040483f5", "fullName": "tests.py.test_login_courier.TestLoginCourier#test_invalid_login", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "12492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_login_courier"}]}